spring.application.name=auth-service
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
server.port=${SERVER_PORT:8081}

jwt.expiration=900000
jwt.refresh.expiration=1800000


# Google OAuth2 Credentials
# Spring Security bu prefix'i otomatik tanır (yanlış key adı yazılırsa sessizce görmezden gelir!)
spring.security.oauth2.client.registration.google.client-id=984998923103-525tf1tq2a7ef35a3kot53vko7teureq.apps.googleusercontent.com
# client-secret: Google Cloud Console → Credentials → OAuth 2.0 Client IDs → senin client'ın → "Client secret" alanından al
spring.security.oauth2.client.registration.google.client-secret=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
# scope: Google'dan hangi bilgileri isteyeceğimizi tanımlar (email olmadan getAttribute("email") null döner)
spring.security.oauth2.client.registration.google.scope=email,profile
# redirect-uri: Google callback'i bu adrese gelir.
# NEDEN 8080 (gateway portu)?
# Kullanıcı tarayıcısından gateway'e gider. Google'a yönlendirme gateway üzerinden çıkar.
# Google callback'i de gateway'e döner → gateway /login/oauth2/code/google'ı auth-service'e iletir.
# Eğer 8081 yazılırsa Google bunu "kayıtlı değil" diye reddeder (Cloud Console'da 8080 kayıtlı olmalı).
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
jwt.secret=?Q>9eSwc2#@HRt(C<z/0YZ[3yH-GIbdL9/o&#-MV}Wl)3ssgXHyq4(^.M9KJ1dK%qvWv0Bq.X-^LJq?@IVR>jF
