package saas.database_initialization.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Structured, per-table metadata extracted from a user's database during
 * introspection. Replaces the old plain-text {@code introspection_results}.
 *
 * <p>{@code tableDescription} is filled later by the LLM and then embedded into
 * Weaviate for hybrid search. Linked to {@link ColumnEntity} by convention via
 * {@code (databaseId, schemaName, tableName)} — no JPA relationship.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "table_metadata")
public class TableEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The database this table belongs to */
    @Column(name = "database_id", nullable = false)
    private UUID databaseId;

    @Column(name = "schema_name", nullable = false)
    private String schemaName;

    @Column(name = "table_name", nullable = false)
    private String tableName;

    /** Human/LLM-readable description. Null until generated by the LLM. */
    @Column(name = "table_description", columnDefinition = "TEXT")
    private String tableDescription;

    /** Approximate number of rows (from the dbType-specific row-count query) */
    @Column(name = "row_count")
    private Long rowCount;

    @Column(name = "column_count")
    private Integer columnCount;

    /** Importance score derived from row count: {@code log10(rowCount + 1)} */
    @Column(name = "importance")
    private Double importance;

    /**
     * Denormalized summary of outgoing foreign-key edges, e.g.
     * {@code "order_items.order_id -> public.orders.id; ..."}. Convenience for
     * building the embedding document later.
     */
    @Column(name = "foreign_relations", columnDefinition = "TEXT")
    private String foreignRelations;

    /** Denormalized comma-separated list of column names */
    @Column(name = "table_columns", columnDefinition = "TEXT")
    private String columns;

    /** Table-level CHECK clauses (multi-column, or all of MySQL), one per line; null when none. */
    @Column(name = "check_constraints", columnDefinition = "TEXT")
    private String checkConstraints;

    @Column(name = "executed_at", nullable = false)
    private LocalDateTime executedAt;

    @PrePersist
    protected void onCreate() {
        if (executedAt == null) {
            executedAt = LocalDateTime.now();
        }
    }
}
