spring.application.name=gateway-service
server.port=8080

spring.data.redis.host=redis
spring.data.redis.port=6379

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=2
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=5
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.requestedTokens=3
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://user-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[2].id=db-service
spring.cloud.gateway.routes[2].uri=http://db-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/devices/**

spring.cloud.gateway.routes[3].id=db-service-ws
spring.cloud.gateway.routes[3].uri=ws://db-service:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/ws/device/**

# OAuth2 route'ları — Auth service'e iletilir
# /oauth2/authorization/google → Spring Security bu path'i yakalayıp Google'a redirect eder
spring.cloud.gateway.routes[4].id=auth-service-oauth2-init
spring.cloud.gateway.routes[4].uri=http://auth-service:8081
spring.cloud.gateway.routes[4].predicates[0]=Path=/oauth2/**

# /login/oauth2/code/google → Google'ın callback'i buraya döner, Spring Security işler
spring.cloud.gateway.routes[5].id=auth-service-oauth2-callback
spring.cloud.gateway.routes[5].uri=http://auth-service:8081
spring.cloud.gateway.routes[5].predicates[0]=Path=/login/oauth2/**

logging.level.org.springframework.cloud.gateway=DEBUG

spring.codec.max-in-memory-size=10MB

# WebSocket frame size limit (default 65536 -> 5MB)
spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=5242880

# CORS - Cookie'lerin cross-origin isteklerde tasinabilmesi icin
# Mevcut her ?ey kal?yor, sadece bu 4 sat?r? de?i?tir:
spring.cloud.gateway.globalcors.cors-configurations.'[/**]'.allowedOrigins=https://querylensio.com
spring.cloud.gateway.globalcors.cors-configurations.'[/**]'.allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.'[/**]'.allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.'[/**]'.allowCredentials=true

jwt.secret=${JWT_SECRET}
